sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
    - cd $TRAVIS_BUILD_DIR
    - cargo test
    - cargo test --release

cache:
  cargo: true
