[package]
name = "soa_derive"
version = "0.3.0"
authors = ["Guillaume Fraux <guillaume.fraux@chimie-paristech.fr>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/lumol-org/soa-derive"
homepage = "https://github.com/lumol-org/soa-derive"
documentation = "https://docs.rs/soa_derive/"
description = """
Automatic Struct of Array generation
"""

[lib]
proc-macro = true

[dependencies]
syn = "0.10"
quote = "0.3"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "soa"
harness = false
